### ISSUE TITLE
unable toBuild 

### ISSUE THREAD

**Issue by abhilashdanda** [p4lang/tutorials#425] opened 2021-08-24 06:06 UTC
While i tried to build basic exercise, i am getting below error.

p4@p4:~/tutorials/exercises/basic$ make
mkdir -p build pcaps logs
p4c-bm2-ss --p4v 16 --p4runtime-files build/basic.p4.p4info.txt -o build/basic.json basic.p4
error: Unknown option --p4runtime-files
p4c-bm2-ss: Compile a P4 program
--help                                  Print this help message
--version                               Print compiler version
-I path                                 Specify include path (passed to preprocessor)
-D arg=value                            Define macro (passed to preprocessor)
-U arg                                  Undefine macro (passed to preprocessor)
-E                                      Preprocess only, do not compile (prints program on stdout)
--nocpp                                 Skip preprocess, assume input file is already preprocessed.
--p4v {14|16}                           Specify language version to compile
--target target                         Compile for the specified target
--pp file                               Pretty-print the program in the specified file.
--toJSON file                           Dump IR to JSON in the specified file.
--testJson                              Dump and undump the IR
--p4runtime-file file                   Write a P4Runtime control plane API description to the specified file.
--p4runtime-entries-file file           Write static table entries as a P4Runtime WriteRequest messageto the specified file.
--p4runtime-format {binary,json,text}   Choose output format for the P4Runtime API description (default is binary).
-o outfile                              Write output to outfile
--Wdisable[=diagnostic]                 Disable a compiler diagnostic, or disable all warnings if no diagnostic is specified.
--Wwarn[=diagnostic]                    Report a warning for a compiler diagnostic, or treat all warnings as warnings (the default) if no diagnostic is specified.
--Werror[=diagnostic]                   Report an error for a compiler diagnostic, or treat all warnings as errors if no diagnostic is specified.
-T loglevel                             [Compiler debugging] Adjust logging level per file (see below)
-v                                      [Compiler debugging] Increase verbosity level (can be repeated)
--top4 pass1[,pass2]                    [Compiler debugging] Dump the P4 representation after
                                        passes whose name contains one of `passX' substrings.
                                        When '-v' is used this will include the compiler IR.
--dump folder                           [Compiler debugging] Folder where P4 programs are dumped
--arch arch                             Compile for the specified architecture (psa or ss), default is ss.
loglevel format is:
  sourceFile:level,...,sourceFile:level
where 'sourceFile' is a compiler source file and
'level' is the verbosity level for LOG messages in that file
../../utils/Makefile:43: recipe for target 'basic.json' failed
make: *** [basic.json] Error 1

**Comment by jfingerh** [comment] 2021-08-24 13:10
This line of the output: `error: Unknown option --p4runtime-files` suggests to me that your system might have a very old version of the P4 compiler installed, before support for that option was added at least 2 years ago.

I do not know how you (or perhaps someone else) installed the P4 compiler on that system, but there are a couple of alternatives here for setting up a system with more recent versions of the development tools: https://forum.p4.org/t/installing-open-source-p4-development-tools/84

**Comment by jafingerhut** [comment] 2021-11-28 15:45
Closing this issue as there has been no follow-up.

I create the tutorials VM using the included instructions every month with updated versions of the P4 open source tools, and for at least 8 months none of them have failed to build and run the basic exercise.

**Closed by jafingerhut** 2021-11-28 15:45 UTC

**Comment by ymym-nk** [comment] 2025-01-15 07:16
> ```
> mkdir -p build pcaps logs
> p4c-bm2-ss --p4v 16 --p4runtime-files build/basic_tunnel.p4.p4info.txtpb -o build/basic_tunnel.json basic_tunnel.p4
> [--Werror=unknown] error: build/basic_tunnel.p4.p4info.txtpb: Could not detect p4runtime info file format from file suffix .txtpb
> make: *** [../../utils/Makefile:43: basic_tunnel.json] Error 1
> ```
> 
> 我遇到了类似的问题，但是我确保安装了您提供的2021-07-31的虚拟机

你解决这个问题了吗哥们，我也遇到了这个问题

**Comment by jafingerhut** [comment] 2025-01-15 15:34
I am guessing from the error message, and the 2021-07-31 version date mentioned for the tutorials VM, that you have likely done the following:

+ downloaded the 2021-07-31 VM image with already-compiled and installed versions of the P4 development tools
+ changed to the tutorials directory and done a command like `git pull` to get the latest version
+ tried to run one of the tutorials, and got the error message that you gave.

The problem is the second step.  DO NOT update tutorials to the latest version.  The version of code in there has been tested with that version of the P4 development tools.

Occasionally incompatible changes are made in some version of the P4 development tools, such that old versions of the P4 development tools do not work with later versions of the tutorials, or vice versa.

If you want to use the latest version of the tutorials repository, then you should also use the latest version of the VM image with pre-built P4 development tools, for example the VM image created and published on date 2025-01-01.
