### ISSUE TITLE
Basic Tutorial: error with make run

### ISSUE THREAD

**Issue by rdhillbb** [p4lang/tutorials#189] opened 2018-08-07 13:11 UTC
I get the following error with make run 

ipnudavis@fattree:~/P4/tutorials/exercises/basic$ !ma
make run
mkdir -p build pcaps logs
sudo python ../../utils/run_exercise.py -t topology.json -b simple_switch_grpc
Traceback (most recent call last):
  File "../../utils/run_exercise.py", line 33, in <module>
    import p4runtime_lib.simple_controller
  File "/home/ipnudavis/P4/tutorials/utils/p4runtime_lib/simple_controller.py", line 22, in <module>
    import bmv2
  File "/home/ipnudavis/P4/tutorials/utils/p4runtime_lib/bmv2.py", line 15, in <module>
    from switch import SwitchConnection
  File "/home/ipnudavis/P4/tutorials/utils/p4runtime_lib/switch.py", line 20, in <module>
    from p4 import p4runtime_pb2
ImportError: No module named p4
../../utils/Makefile:27: recipe for target 'run' failed
make: *** [run] Error 1

**Comment by antoninbas** [comment] 2018-08-08 16:27
Duplicate of https://github.com/p4lang/tutorials/issues/178

**Closed by antoninbas** 2018-08-08 16:27 UTC
