### ISSUE TITLE
failed to connect to googlesource.com

### ISSUE THREAD

**Issue by ls760008979** [p4lang/tutorials#350] opened 2020-05-04 02:24 UTC
When i use the script provided here to install P4 development tools

> https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4dev-v2.sh

as it going to install grpc,it raise problem like this:
![无法连接](https://user-images.githubusercontent.com/30166591/80932215-2542f000-8df1-11ea-9c04-b7e6e8a4db4d.png)

What should i do?
I have confused for days,please help me.

**Comment by jnfoster** [comment] 2020-05-04 02:25
Is it possible that your government is blocking access to that URL? It works for me.

**Comment by ls760008979** [comment] 2020-05-04 02:29
> Is it possible that your government is blocking access to that URL? It works for me.

I do think so,I've tried many methods but failed.

**Comment by jnfoster** [comment] 2020-05-04 02:31
I just accessed it here without problems. So it seems like the issue is on your end. 

In any event, this issue really pertains to scripts in @jafingerhut's P4Guide not the Tutorials repository. So I'll close this issue here.

**Closed by jnfoster** 2020-05-04 02:31 UTC

**Comment by jafingerhut** [comment] 2020-05-04 17:39
@ls760008979 As far as I can tell, the failure you are experiencing is from the last of the commands given below, copied from the middle of the install-p4dev-v2.sh script:
```
get_from_nearest https://github.com/google/grpc.git grpc.tar.gz
cd grpc
# This version works fine with Ubuntu 16.04
git checkout tags/v1.17.2
git submodule update --init --recursive
```
That command works for me from San Jose, CA public Internet access just fine.  I can't give any recommendations based on technical/legal knowledge of your country's Internet access, but perhaps some VPN software would let you download from the public web sites that distribute the open source software that the `git submodule` command is attempting to download.

I can say that if that command does not work for you, then nearly any other script you find for downloading and installing open source P4 development software from source code will likely have that same command in it.

Another alternative that may work for you is downloading an already-compiled version of the software as a VirtualBox system image, e.g. the ones linked from this page, which is also mentioned in the README of this p4lang/tutorials repository: https://github.com/p4lang/tutorials/tree/sigcomm19#option-1---download-the-vm-image

**Comment by ls760008979** [comment] 2020-05-06 03:08
> @ls760008979 As far as I can tell, the failure you are experiencing is from the last of the commands given below, copied from the middle of the install-p4dev-v2.sh script:
> 
> ```
> get_from_nearest https://github.com/google/grpc.git grpc.tar.gz
> cd grpc
> # This version works fine with Ubuntu 16.04
> git checkout tags/v1.17.2
> git submodule update --init --recursive
> ```
> 
> That command works for me from San Jose, CA public Internet access just fine. I can't give any recommendations based on technical/legal knowledge of your country's Internet access, but perhaps some VPN software would let you download from the public web sites that distribute the open source software that the `git submodule` command is attempting to download.
> 
> I can say that if that command does not work for you, then nearly any other script you find for downloading and installing open source P4 development software from source code will likely have that same command in it.
> 
> Another alternative that may work for you is downloading an already-compiled version of the software as a VirtualBox system image, e.g. the ones linked from this page, which is also mentioned in the README of this p4lang/tutorials repository: https://github.com/p4lang/tutorials/tree/sigcomm19#option-1---download-the-vm-image

Thanks a lot！

**Comment by ls760008979** [comment] 2020-05-06 03:25
> @ls760008979 As far as I can tell, the failure you are experiencing is from the last of the commands given below, copied from the middle of the install-p4dev-v2.sh script:
> 
> ```
> get_from_nearest https://github.com/google/grpc.git grpc.tar.gz
> cd grpc
> # This version works fine with Ubuntu 16.04
> git checkout tags/v1.17.2
> git submodule update --init --recursive
> ```
> 
> That command works for me from San Jose, CA public Internet access just fine. I can't give any recommendations based on technical/legal knowledge of your country's Internet access, but perhaps some VPN software would let you download from the public web sites that distribute the open source software that the `git submodule` command is attempting to download.
> 
> I can say that if that command does not work for you, then nearly any other script you find for downloading and installing open source P4 development software from source code will likely have that same command in it.
> 
> Another alternative that may work for you is downloading an already-compiled version of the software as a VirtualBox system image, e.g. the ones linked from this page, which is also mentioned in the README of this p4lang/tutorials repository: https://github.com/p4lang/tutorials/tree/sigcomm19#option-1---download-the-vm-image

The link "inside China" doesn't work

**Comment by jafingerhut** [comment] 2020-05-06 04:44
Have you tried the link "outside China" to see if it works for you?  Just because it says that isn't a guarantee it will not work, but I am not inside China to try for you.

I do not know the legality of this, but I suspect many of your fellow China citizens may use VPN software to get around some of these issues.

**Comment by ls760008979** [comment] 2020-05-06 05:22
> Have you tried the link "outside China" to see if it works for you? Just because it says that isn't a guarantee it will not work, but I am not inside China to try for you.
> 
> I do not know the legality of this, but I suspect many of your fellow China citizens may use VPN software to get around some of these issues.

It works,but with 20k/s speed,i'll try the VPN. Thanks anyway!
