### ISSUE TITLE
ImportError issue: No module named p4_mininet

### ISSUE THREAD

**Issue by Juniortheone** [p4lang/tutorials#242] opened 2019-03-05 08:08 UTC
I have been trying to run some files in the p4 tutorials but every time I try, I get the above mentioned error. I was advised to add the directory to the pythonpath to which I did but it's still not working. It's not available when I check by using python -c but there seems to be a swap file available. Can anyone help me please? I have been stuck on this for days and every time I check online, I get nothing tangible.

**Comment by jnfoster** [comment] 2019-03-05 10:51
This seems like a duplicate of #238.

**Closed by jnfoster** 2019-03-05 10:51 UTC
